[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[functions]
  included_files = ["./src/assets/serviceList.txt", "/src/assets/serviceList.txt",  "./src/assets/serviceList.json", "/src/assets/serviceList.json"]